### ISSUE TITLE
Unable to create LineUs object due tu error with ServiceInfo object

### ISSUE THREAD

**Issue by BenTeoNeb** [Line-us/LineUsPythonModule#7]
I installed lineus in a python 3.7.5 virtual environnement and tried to create an object and it failed. The error messages says that an unknown attribute of the ServiceInfo object is called.

Is there a specific library dependency that has been missed ?

```
>>> from lineus import LineUs
>>> tmp = LineUs()
>>> Exception in thread zeroconf-ServiceBrowser__lineus._tcp.local._123145557975040:
Traceback (most recent call last):
  File "/usr/local/anaconda3/envs/robotdraw/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/anaconda3/envs/robotdraw/lib/python3.7/site-packages/zeroconf/__init__.py", line 1725, in run
    state_change=service_type_state_change[1],
  File "/usr/local/anaconda3/envs/robotdraw/lib/python3.7/site-packages/zeroconf/__init__.py", line 1479, in fire
    h(**kwargs)
  File "/usr/local/anaconda3/envs/robotdraw/lib/python3.7/site-packages/zeroconf/__init__.py", line 1577, in on_change
    listener.add_service(*args)
  File "/usr/local/anaconda3/envs/robotdraw/lib/python3.7/site-packages/lineus/lineus.py", line 440, in add_service
    line_us = (line_us_name, info.server, socket.inet_ntoa(info.address), info.port)
AttributeError: 'ServiceInfo' object has no attribute 'address'
```

**Comment by BenTeoNeb** [comment]
Looks like the attribute is no more "address" but is now a list "addresses".

Fixed by:

```
    def add_service(self, zconf, service_type, name):
        info = zconf.get_service_info(service_type, name)
        line_us_name = info.server.split('.')[0]
        line_us = (line_us_name, info.server, socket.inet_ntoa(info.addresses[0]), info.port)
        #print(f'Found Line-us: {line_us[0]} at: {line_us[2]} port {line_us[3]}')
        self.line_us_list.append(line_us)
        if self.on_found_line_us_callback is not None:
            self.on_found_line_us_callback(line_us)
```

**Comment by robertpoll** [comment]
Apologies for the delay on this, but thanks very much for the detail. I've just pushed v1.0.2 of the module that should fix the problem. Let me know how it goes.
